[package]
name = "shellcanvas"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lib]
name = "shellcanvas_app"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
anyhow = "1"
async-trait = "0.1"
serde_json = "1"
tempfile = "3"
uuid = { version = "1", features = ["v4"] }
shellcanvas-core = { path = "../crates/ssh-core" }
shellcanvas-services = { path = "../crates/service-contracts" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["sync", "time", "fs", "io-util"] }
