[package]
name = "shellcanvas"
version = "0.1.1"
edition = "2021"
license = "MPL-2.0"

[lib]
name = "shellcanvas_app"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
anyhow = "1"
async-trait = "0.1"
serde_json = "1"
sha2 = "0.10"
reqwest = { version = "0.13.4", default-features = false, features = ["native-tls", "system-proxy"] }
keyring = { version = "3.6.3", features = ["apple-native", "windows-native", "sync-secret-service", "crypto-rust"] }
tempfile = "3"
rusqlite = { version = "0.37", features = ["bundled"] }
uuid = { version = "1", features = ["v4"] }
shellcanvas-core = { path = "../crates/ssh-core" }
shellcanvas-services = { path = "../crates/service-contracts" }
shellcanvas-adapter-runtime = { path = "../crates/adapter-runtime" }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["sync", "time", "fs", "io-util"] }

[dev-dependencies]
tao = "0.35"
russh = { version = "0.63.2", default-features = false, features = ["ring", "rsa"] }
rand = "0.10"

[target.'cfg(windows)'.dependencies]
windows-core = "0.61.2"
windows = { version = "0.61.3", features = ["Win32_NetworkManagement_WNet", "Win32_Foundation", "Win32_Graphics_Gdi", "Win32_Storage_FileSystem", "Win32_System_Com", "Win32_System_Com_StructuredStorage", "Win32_System_Ole", "Win32_System_Memory", "Win32_System_DataExchange", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging"] }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"
